stages:
  - deploy

deploy_to_cloudpanel:
  stage: deploy
  tags:
    - cloudpanel
    - shell
    - myrent
  when: manual
  variables:
    DIR: "/home/myrent/htdocs/myrent.hr"
    OWNER : "myrent:myrent"
    BRANCH: "$CI_COMMIT_REF_NAME"
    SERVER: "185.166.39.216"
    REPO: "myrent.hr"
  script:
     # 1) Ensure runner trusts the new server fingerprint
    - mkdir -p ~/.ssh
    - ssh-keygen -R $SERVER || true        # remove stale entry if it exists
    - ssh-keyscan -t rsa $SERVER >> ~/.ssh/known_hosts
    # 2) Run the script
    - |
      ssh root@$SERVER << EOF

        # Check that DIR exists
        if [ ! -d "$DIR" ]; then
          echo "Directory $DIR does not exist - exiting"
          exit 1
        fi

        # If $DIR doesn’t contain “/htdocs/” then exit right away
        if [[ "$DIR" != *"/htdocs/"* ]]; then
          echo "Directory $DIR is not under an htdocs path – exiting."
          exit 0
        fi

        # trust the directory
        git config --global --add safe.directory "$DIR"

        # if it’s not yet a git repo, clone it
        if [ ! -d "$DIR/.git" ]; then
          find "$DIR" -mindepth 1 -delete
          git clone git@gitlab.com:myrent.webs/$REPO.git "$DIR"
        fi



        # now update to latest
        cd "$DIR"
        git fetch --all
        git reset --hard origin/$BRANCH

        # change permissions to allow web server to write to the directory
        chown -R "$OWNER" "$DIR"

        # your build steps
        # composer install --no-dev --optimize-autoloader
        # php artisan migrate --force
        # php artisan cache:clear
      EOF
pull_from_cloudpanel:
  stage: deploy
  tags:
    - cloudpanel
    - shell
    - myrent
  rules:
    - if: '$RUN_DEPLOY == "1"'
  variables:
    DIR: "/home/myrent/htdocs/myrent.hr"
    SERVER: "185.166.39.216"
    M: "Push from server"
  script:
     # 1) Ensure runner trusts the new server fingerprint
    - mkdir -p ~/.ssh
    - ssh-keygen -R $SERVER || true        # remove stale entry if it exists
    - ssh-keyscan -t rsa $SERVER >> ~/.ssh/known_hosts
    # 2) Run the script
    - |
      ssh root@$SERVER << EOF

        # Check that DIR exists
        if [ ! -d "$DIR" ]; then
          echo "Directory $DIR does not exist - exiting"
          exit 1
        fi

        # If $DIR doesn’t contain “/htdocs/” then exit right away
        if [[ "$DIR" != *"/htdocs/"* ]]; then
          echo "Directory $DIR is not under an htdocs path – exiting."
          exit 0
        fi

        # trust the directory
        git config --global --add safe.directory "$DIR"

        # if it’s not a git repo then exit right away
        if [ ! -d "$DIR/.git" ]; then
          echo "Directory $DIR is not a git repository"
          exit 0
        fi

        # set path to project
        cd "$DIR"

        # Set git user as DominicGalic for push permissions
        git config user.name "DominicGalic"
        git config user.email "dominic.galic@my-rents.com"

        # push changes
        git add .
        git commit -m "$M"
        git push --force

        # your build steps
        # composer install --no-dev --optimize-autoloader
        # php artisan migrate --force
        # php artisan cache:clear
      EOF
